---
- hosts: deploy
  become: True
  tasks:
    - name: Install python pip
      apt: 
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
    - name: Install docker py module
      pip3:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: petclinic
        image: "oleksandrmykhalchenko/petclinic:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
