---
- hosts: deploy
  become: True
  tasks:
    - name: Download setuptools
      apt:
        name: python-setuptools
        state: present
    - name: Install pip
      apt:
        name: pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: Ensure docker launches on boot
        become: yes
          command: systemctl enable docker
    - name: Install docker-py
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: petclinic
        image: "oleksandrmykhalchenko/petclinic:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
